#!/usr/bin/env python3
"""
Nova OAuth Wizard: OAuth-only Cloudflare Worker deployer.
"""
from __future__ import annotations

import base64, hashlib, json, mimetypes, os, secrets, ssl, sys, threading, time, traceback
import uuid as uuid_mod
from http.server import ThreadingHTTPServer, BaseHTTPRequestHandler
from pathlib import Path
from typing import Any, Dict, Optional, Tuple
from urllib import request as urlrequest, error as urlerror
from urllib.parse import quote, urlparse, parse_qs, urlencode

if getattr(sys, 'frozen', False):
    BASE_DIR = Path(sys._MEIPASS)
else:
    BASE_DIR = Path(__file__).resolve().parent
STATIC_DIR = BASE_DIR / "static"

# The UI travels inside this file.
#
# It used to live only in static/index.html, which meant the tool could not be run
# without cloning the repository, which meant every user needed git and three
# commands where one would do. static/index.html is still the file you edit; run
# scripts/embed_ui.py to fold it back in here, and scripts/embed_ui.py --check to
# prove the two are in sync.
#
# A real static/index.html next to the script always wins, so editing the UI and
# reloading still works without regenerating anything.
# --- BEGIN EMBEDDED UI (generated by scripts/embed_ui.py, do not edit) ---
_EMBEDDED_UI_B64 = (
    "H4sIAAAAAAAC/+1925LcxpXgO78iVbSFKhNA41L3YrVMU5LFFUUxREqaWYWCgSpkVYGNKtQCqG62mh1hOazLgyJ2H/bBsfuw"
    "G/MwshWSOJLlmfGLvqPbetMP7C/sOScTQAKFal6k8SViLLMbyMvJk+eemSfRV5978fXrd//x9ktskS7D/UtX8RcLvdV83OCr"
    "BvODeNwI07iBVdzz4deSpx6bLrw44em48ebdl41+g+1lFStvyceNw4AfraM4bbBptEr5ChoeBX66GPv8MJhyg150FqyCNPBC"
    "I5l6IR/bOsv6GbMgHU+jQx5vgZ5GYRRDjwVfcgW878UHLAzmi3SrR4pNDeqndLhs9ay+NRCt0yAN+f6t6NBjbwfvebF/dU8U"
    "XbqapMf4e+9nzPjB/7vEGFMG0VkYwcyZz9dhdMxj9uYNE5vcjQ74KmFezGFGs5T7bBZHSwbzEL1vx9GDY7b2VjxkzVv0dqeN"
    "HZN4uuclwJdkj2r3PH8ZrPaClc8fmMjZFksigBMkLI0i4HMUHSQwxgEn4NQH4QQpsCZJvTBMTHaHhzMDyeYFK+4P2SpiR3wy"
    "g4JEx5frL96i3yueHkXxAc3glWiTcBZvQl6gTtCH9DiJvZXP5rHnB8ALBujMoriY3xJ4iVCiVXhssmvTNIgkOZIoDHzmTafQ"
    "DQblICA5GPPSD2eQwX62d2kYR1F6AgioojZEARtBIQhCsoln3pQDSjCLlD8AVEj8kKwwB5/PvE2YIigGQjOZD6WsjeBNUOGy"
    "NbW47WDBFARheNm2bNceZO8ONJhYvm1jwSzgoZ8XCJDYY+pYTm9Eb9De6ToTty2q0wfDy3zA/Vl7RG9Q7fFJd0qvy83wcm/S"
    "bw/acjaCmmIywPN0k2SYe1OA6/gu5yN6Qzj9TmdGo0YHw8tu23cHhLUPk5z1e3aPUD5awVtnYrWdkQQEswjDMjQqMhYAZeZP"
    "Z64sDFYA12rbju1hSUjvslsGK4lm6TCeT7ym29Yd29Ydt6+bttOSMKAT365321m9z/m6DPRQgWl3+3q/ozvtHsC0oA/VFzDV"
    "eleMeSjQnvh9b9YXEKMDBWTHITTsjitBUn0BUq13oZ4g+HMFgtPu67bt0j8CQfUFhFI9YkUg4mA1ryFER1YnC8+PjoYWs9cP"
    "mMUEoA5MTf4zLaelQ60D1a4FP6iFpeN/ZjuDsvIOxRg9va8PdLMvRgfJKil0rqc6W2/iNVgGLxXGIEpTMBEhn8F7xKbH3iqr"
    "SqM12gHGYjTsOks9MIyFRSGwXkxmB2xWAobKZK9hobAcUoyx2RBJ5cVGhkSzb/l8rl8e+G0+mzDrp/ply5n6M5fZlvVTOTNQ"
    "/MPhJg6b4F1SbxgsvTnfSw7nVx4sQ/2n7nV4ZPC4SsbaIk3Xw729o6Mj88g1o3i+51iWhY01JjyfZnc1tuA4EfGMvu4X0YOx"
    "ZgHtnTb8X2OoEmNtFa24BroYgx8Yaz91XKGvWZEhATp5AU5u6q3HWhxtVn6p+H4UrLLyn7ovAdbrKDzGGraGqhRw77IB8JjZ"
    "HWb32UDbE80Qd3hqZMyc8wh8anysVyx6RmUk7CYZorCgfIPdXA4H2XM4H9pd8ZKsh3YbHqkTepFhcpykfGlsAt3w1iAYhijQ"
    "tTt8HnFwipr+RgRSEunaKzw85Gkw9dgtvuGafi2G8EFPvFViJDwOZgVUY+YNtbe894J46aUrTQV211tES08vhr0AyjJaRcNN"
    "QL+TNRh9/c7Lr8Gz8Qafb0IvBrgvMyzQ9Nf4Koz06+CqotBLdO1mMOGxh75LNshhCPjcS/hwupkEU2PC3wt43DQdUGBUX90G"
    "qp8KR/QOyp5BMcxYowBHe3fLOVH5KHc3s/asO5so7mZG/yvcTfkd7PqsNxvMpoq7kQW5u+Fd7s3s3N34Pnf4pHA34L+6jpO7"
    "G9drdzvTzN10Zl2v549yn2JxryOcEfmU3tT1uJ/5FKvd63d6mU/xp+DYuplPmbQ7LrjRsk+xeK89sCo+xZp0vX7JpxRTFj5F"
    "dtv2KXZbt7sd3R50c2Nd8ilqfdWnWBPwjm6NT3HaeqcP5hd8htWr8SlKvdNVfYokzrZPASwcS+8jwD4CrPqUoh4B1ngUqAVv"
    "gA4hw6jsUYr6HEDhT8DbtIEGPazt17kTJ3MXAKYNeIDHsNrkTdCROP2sGuq6FrgtSxC77FGcNritdhecEahFP8PiInsuyCXs"
    "eX9gT5y/SXsuFOKvZs9PL/3sZBI9MJLgPWToJIp9HhtQMjIgsj8IUiP11sYCpkZ2RSydhikE7WC+YqD26SVcTOiTyD8+AW7M"
    "g9XQGq0930dw1uklqgCST7zpwZxwHR56cRONU2skoIn39EFrJK31MgiPZSmWEMuoCrDkwmXgLA1B8qFtdkawtslfLetwQVyW"
    "MxBdl2BAF4iUt8KFZgAm1x9hxG7ANGDSWBWt02AJY9zk82AShEF6jBTCCb5D62Bt5mnvMppSPapQ0qrg1uucXvJO1Jmi0WmJ"
    "oX0+jYRjGKJkQMvhApe6J9XaDaKIgMEVzKLpJjEOgySYhPwk2qSkqahlYk0kRvGmrZGsM6LZDFaC2GQkOSxdNJASWLSBqGtF"
    "MxoGqwWQIpWckW+nl7I1L4ZhwMqYZQskE16QvesoCQjRBFzywfEI2oEcvGfQenPoWCM/SNahdzychfzBCMg/XxkB+NxkiCsO"
    "HiO/7m+g8+zYkOvyITlIcIjpEeer0dwrooVMvmw0L9PQW66bGFPoncMjHe0JScyWxIEtaY2w1I+jNboHGHc4CTdxE+G2com/"
    "oAmCzVQEQ9WhXaH6xCelMsNoHp08bs44JYyLSHKOhMB0LWtUlXWeQmsDyYGTNkzL5ks5BgNVPiGjMXSQvVLs6DkbfhJG04MR"
    "IjFEe+Rt0gh6I5XjKExyLIMVycpFyPZRXExUhfpucnQX47uMRy48Y99C+GqJtsUtjEZaFXEVNRhPtjI8mJTenDMgdtNNnID0"
    "khEEzBVyOjXURtMhKOi2FbyFe1I4LnHoFlRGf1KyYctNaSKKmUQ49Cq0hDox03YTSQKMAFt60XerTkiVMmNpKComtNLIBMqo"
    "LUQEVENtGS9hf4ovkZ5PKBhVtZXFkqQKueh5i54KT59BPrLoN6cArDh3s3/LczwhWwTC9bXEGKJZPUdGau/M9/lOSzGqawg+"
    "cBqb5aowrEextwaP+kDKZtdBacw8LClxLqrCAqLO622wgCjGrS2zSIVdMvjlgXEvtxgWDH4kvA+xGuw5rKrluJnR65IZ4Md8"
    "EkdHTyEpaAZ6QgYUpoD7rtHKLa4qZh8mwcj048Ngy6kNBgNV0GrEydkhT47gppzZcDjhsyjmYoklhFvTpGArct3dwqADdqFG"
    "xaT/eFCEx/gfGMjcZVNQ3irbakTpHdx81+I0hPAjJ7xKjoGkBpLlVHCRLeyTEqWlRJidGFbUbRNFBcMTeGuVyN8D8m/7HMfh"
    "S8S/HN04mUjSzpDFkL0kPSi+w4kHxggXudtBVI5iZaRVBKv0sBJDtSGGMjG+P9miKq4Ayq5bVBvTMFgPEZVRbWFNICtQWp9s"
    "iV4e1xbq2HGmC9WyuCTEZay7HYUU6xjmeazoXpLyNQu5P+dKNIWFa7AhOyMHLDBUnSRXj6sM4jv2p/FO8oAs5iGEkIdcCJXN"
    "bKa6vEpgRuBB1vg0s4dgky6OBvIhh0NvBlUVbcnx8Cagg5uUU2hoK7GKjeqztTrwhcoHKwhcDWlXaN7DqRdOm6Bh7AqzexiU"
    "ldpALC9aGGqTSyVEQy+BlcwiCP0M54wIIghXmi68pEmvpg9Vrax9nf/E4VuycykkzjmQhcO2tCFOR4nYOrVWRDGuT+l/y0bW"
    "2RVmAvoBrIiM1WYJof50mHoT3MzC9+RZbWg1JMqoj9HIzsij7CfV0Kk2gKla0faWFc0GRcbVDitsbY17zphZHRk3djKwRuhN"
    "eHii+rEtA+BuUUJxrJJNhUnBaFKxD0jLpLAM+Fq7jlbj5PrIqS7copeqPxJ14qWVRxdK4GGQ7lIYdypQYgtHpUG3Rsxqli/o"
    "SvJQxmIdNCRbDiIDX+sgkAubybapVk3ytkFWByVcL7DPnjxrLFa66UqY1m2LSRDwh1ilWmQYsf0kmP/wSFraWmSWnEq7vFAh"
    "Du2OqsuWwK0Nt9TtjGwPYJtxVkfEALuVuF5XK7JZWRdV4vWjBRCFRuXAbKJqOUq/YJWkUzMI2pZPGcXrFwT3kpEyvN81d2PR"
    "Utqi9BzykxydIeU1NM1Bv6M0g7Au8SYQBLx7EiGV0+Oh2cnWL6sITUUYHeE+VQ5HeigEMF9ESXqyywjvWHaMtheMOaxdM9wN"
    "EW3aFsBchWAGXFEgfD2pOrRMYXZFOdXdHlJr1Rq1n0L2nboo7UIv92ROTixQTsUUlS0ZW90sINtYCuyVaaB/rhA2Azc5qd0m"
    "LZRXNjQDEJJt5h3u9nOHecyS9yfky21Qh0tNJrUNcq7TqZHKdm/JDURpfVJeRtq0GBV+tLJXtXtDTLCwShHFrtPiNFitN6me"
    "8BACWRS5wsNm7Ghb5b0eVy4Zq+Sj2Ty9f82Er5Z1W4a4Yngr5u5Cu1W471rjRYQYDoG2U76IQr+yP0FiJtqQ7kuSZYZg186F"
    "6EH70FkPesk3o9FK1UdWNaFbsQDGTXgAX/DNg9WQF+MaUoDM1nnV8hLnDDrNybR1wQ9VJTZiDl1T6CafKn2LqB3FRCQ8SD8s"
    "pUVdadCOYcV/VZbrcjJ1Q1CegzKCokRLniQwCUWNlsn8ZNsS7ha+CyOhTme0rYtbQn5Ko5rBahb9CAG0cDYIMDrYBicPNGvB"
    "ycPMXeB4XOOz5AFnLTx5uFkD7zIdkr+WzId8uU6PK+vCnDsiS4+t42geA6NyJl0WFbdl+RMdAJDzqzCr6lsw2l0Hq5VYXVei"
    "SWEypYVTVpT0XNlJyj2dU7ueE6QCf1SjtDUrU28FmiZOfQA7ZvYTJs5iYdk+w4RO2vn5+QE/nsXgBBKGzU7SSAmL4ij1Ut50"
    "u3hm2zpVaAwExMy5XP5xGWdMPCLCE9FV7IQp3ZgZTH94NJ57E0yDyre2rS1a11LscWK/5WBqRT86ENFGZW4XBB6VxrCqyve0"
    "Ll69QUfBCDwTPhHpP0tvusBDZjD26AYgwMIoNZF5QHPO8g0kHY8hGKZmHsN8wg0EMxyasiARuVyTwA+MAJNkMLM1idibb9xM"
    "dBb4IgVx7SXJUYTL4CmEHSLFc8JBMohW0IPyjbY2q/8D3HhueNs10eeFlrbXqT2jQP86A1KIpaO3Oj4C10/qotCbDvtX8yeI"
    "/5Q+NWfN5QbTyOf5xvD2CTamJrW2I65dWw/OBUR1tuxG5fgWenQr5k4cjlfoMAySJqKte7ogSetkswqwxEARGkoRKp1Te4li"
    "POi1tCk3Cx7Aukp6PzouRW9MelpYJ3pCyP9A24n1x8rIkVKINC/2TjC3xe4/9QqlGv9mi0NrpMSFspCZTqcS9jEmYxEDVGaV"
    "JiJGynYfO5Y4skKSmMkiOsrXnrYaxUcQ7ys70/h+oki+62TbJ+p2FjqqaBp4YdlEX7Cx0V5v7aFUIhO5s01gQbp/rIPJvmK9"
    "+487mNza0fwxTnOzKe06N9yhbvWJIxk0xQcoM7TFXj0ykfzJydb52/biM29cMSlbtbtOoi+ZiwBMTSWG+vmS+4HHmspZShe8"
    "ZwsZK3Y5c/PQQ6ShtH6/1ZK12T6buouKBwfKCrDs404xKJFYrGM+43ECawF/M+U+WD+5ZY+vhNPPTgpOG/5GEt207GXCnguW"
    "eEXFw9OjApPtzR8x9dNLV/fkFZKre/IGDeYSwS8/OMQD2yQZNyYe3rBhTC3DTA8qhGLMTMvyyxq0kel02vSjwXAv3wCi+3w1"
    "bqTxhjcYrctwj2ncmHlhwiUYhM9nyf5VEbD9Mr9/4Y8bq+jQw9TpBntgjxu20zetboMd47PtOGYPXh44WGF1zX4HauCl7ZqD"
    "XiNP7H4Tgj/Ae5Pw+A5u5L2+ehOHvppg/pDIRho3TAtQTvJoc9yQKdiNvUpDu9JMpGdjs70y+lBAs8qmuPbShUi8a2Cu3+Vs"
    "Zq0Gg3m+Ztv9jtnp6XZ7YDru1DJgFv224fRgfWT0HbNrdLumPTBApsye0bbMvmvYA9Blo98zB33DxvkbtgO/HJ1auq7p6tCk"
    "1zU6XdNx9E7HHAzouaMPOma3Hxqm29e7HRdKTGuguwOANDUt6OaaHRtqXR0Auj3DRaiuGM60Hd0ZmN2O4VpmB8C6QDwE2x3o"
    "Xcd0YWTwHJjzb3Ydo9sx+z0dpmYMbNPqGXYHwhDDsbC/3TPbDuLp9I02TLFNODtGzzJtG5GDhm3o38GOjgv9O1Mcy273cfqD"
    "nul0Dadvm234BSRx+zC0bfZtowuQB0gfyzFst4+IwEsXmlltIILuwMAh1ECR3gYKX7c7AyA34Nw2e0C/PtTrDtJjQC+27uIw"
    "LiBldfWejZI3tbBq4Oowdbzm4ADuA/jVJgLCL7sDtDUB7R6+AwmAEY5p9+kFJgtCCxwPzX7fQIhdd4rz7LQBWx2kYNA2Bl3K"
    "vbZc7NvvI1Xb+KwTD3swehcLoE0PptrXoYnbDm3TaQMA0AJnatpdZAre5KCZIZbOQIfZtgHXXtt0bITQ07suztW2+jQX4J0D"
    "v0DuYBwbuDLo68A/AAAaiCgNLBNaA8/7utNzTeAc1IIEgfgNDOABlHeJSR3gpasPgOogxtBwEEKvDgi2C6hNsVfXaLfNdg/J"
    "COy0gU+OeEEBgX5E9IHRgwm03f8KmiZsDyaOZmYIVsp0Sw4K8REt1h6YrKrpytLMMvOlWjVMVAKjIFKVWHq8BiMlXhpkiLCB"
    "gVcPZQcsj1bTMJgejBtgGW5CfVPjK63V2H/p1tU90fdxAGdeHZSZh1BevlZAyWYDSNcClEil4vYhgpePOfA0ms9DfhdLmy1p"
    "ncmNjRt3qUrcUmQQPNClMdF///vffptjUZBV/ir5CgyXtpwFZjE0FC5l5TJtRKJqZK/7N0sXD+n+3rXbNyCCPuCrgrkAbGHL"
    "rnQfsiHuSJaGQPPf2M+uTVJX8HS27L+W3ZPNpLH/othCOY42MYuOVuJykLhFkkai+HoYbfxZiJf9vOkUAqEUVt5g0MGZsoRP"
    "N3gJEII+cPUmAyKzt6P4ACfw6lt021Pc0aCF5Is2wzTvCYRedHdwGnNaceJVQxjKvLq3VihdoafMyWAYzAjiYcmNlR9MvRTv"
    "kap8vcPTzTrfGGrsl3UCO2c7TA0GasERGN6zy6BA3ABNYBWV8rxzVaOAuAUeVsbqhSPKLGMBLODhNFpyIL6TEz+bDlA/a0mc"
    "eAmX55QazeLNKmEo6HgtFABACMVjk/1jhRsJTA3vsogVeci9Q54IlsmtAZO9AeHNMXJysglCX1Su4+AQyK6w+gVJ+PIEs4PW"
    "XaZBaQbRVj4ZeFd0bx7dAerYoHf7v+Qpo50B7tdqtzI0HnIUEdJWqEWp/A0ZUWBQ18hS+RsgjnieeV1cLS5l8zdwF6BRTehv"
    "UGjf2Eroz8q3Y7n9q7itwgAXwOEYwIIra7BsDIjK5BUEqADhgmbggzBIoigI450+wy5v9bw2a9POu836zDp0RbPCuCvSCnQV"
    "NLk62b8t+YcaRbeVQW8m+8BOITwgMgmGkNlmBuMPpnydyt2gkKShECId5SzXfqnfpsqWXHN2akFFJe2qKtioCneEiRCmoxj/"
    "YtWwhWooMh+t8R42wPFA7I8YGBOTXVuDoh+SdcJd4BRnreOvFSoPp60CnDWpE+6MkZ0CYPCqWlm660gmyfzRFCLyNuniFyWV"
    "IB14/RqUo1bcjOZ1VHm8fjA8BPwbVpJpEE/BtU4f4BIFiHMsfsPCYVDSBgjK2GAB8XCXHu0OPZea2A5zPbw805HqYuE9mlKB"
    "Yfff2609tiGIBdpzY8VuwPOQdCaY0W6pIl+0cXoENMNTc5I2kKRNvMrVRNKOvXX7FtA2Tn6gsjhVZXFQWa4vogh8JA0odfJi"
    "RXGEotwOpgfVGWU+G4RbnpdEq3r5Lk6IgVLkSDPgIS5ggXMS1r3ALylljiJ1glUjLfeps9oDmEMVu6T6mRyOU+twXFSt6xDz"
    "BqtNjTY9MXvcKntcZM8tIJRgDkQX8AvMzsXscQV7wOrIyGcdc8pWgeCHVD/xZmCy8BsM0VJETSa7CQ4dDTqGo8wju3ZMnfHj"
    "DOjdn4qJrnEkmXhE8dk9bAgRCr1g6As29D5yDctzTtL2DQFQezHlHBtYvEkjY85XeLWWozGAdwxaQp4C86LZDOzGmofhdMGR"
    "QXL7Y5dl24n+waHE/+DwXh5XNvbVKHMX7qUefxXkfVsi79uS8GosvAPtrO1/IMbPpHJuReX8SKwiUOfkemIVHf0ArWtXta6N"
    "WidAg0Z8/6t/vlDdhJm7IwL6/TvobrNeqsIUTW8X6wR1GSXPeslw0RqKKiVCR16QAnCepkJHA7zts1nTKHLF9bTT7tQszpXj"
    "QsXXK0gGU8T6R3L+uOfxozj/6g3YBvhqCIMh8GXg3eH3gPVyd62ubhWmd5DptOahlQpYvRhXMwrrFZmuMbodMrqMtnrHDfW0"
    "0Fk/aOy/Dr5dLohouYvhNJ6WJ2CNafVIcaTJ7sCySn5EJvWCMJFnpwlEliK+Rttdb4uLozOBkni/BtN4vELW4d1FvJ9CUTsG"
    "BjCKpgaz5lEAPubIvEeTfjMOW7IAW25V6tq9SeitDnBPhui1lB85eswmTxkblmc25nh5cy/Y4bWlBfEg/gLy/mck/ONGwp3d"
    "kTDpgnDzienzQ+b5PqXV4KZ/QrEwGDkdi2H1dX2T4DdiXoyWwEmxusq2fnB5pkaHoFj47al04YmPWIEWP0XQjCdcNYZRnLMV"
    "XPfYIuazcQM/E5AM9/bwjGGN3+EyIzqe3GvAYjGe4zmGkGlgACd5wIkB0quIzqBi/MAZ7ayNG2/zSYI7QKWtJTJGR7ImG/4/"
    "xa5W7Pa8nfxJzSXfC2Jk0zNw5i4sJOaxt8Sv3oFvDCu7utXav2U25UR2bKB+23SZYw6YbZv21DD7pgs/mG3iRhEMGbbNLvwG"
    "wkNpZ2o6Zg8ebWrSNd3QMdsG/AMwbQbMnEJhG3ubNjYwzG7oGjZUTk0b4MK7AZXwz8Z/76k8X5KbRnRsy+hB2y6MPDB7z8jj"
    "eyIs/gGclgBq+Sxj7r8HLttd5liHQO6u5xKTxBagZdBJktl+BTh2rVTDgAV9s/2WYyHtFa0e4L4jqnWftBr4XVJax94xEp6o"
    "uqZb1vAOsLvjoQHAf5mWd5+G3eBA0s2Em7Aa2ft5bn+D+Bm4DmHfXQBVZrcs/LvQ6myLGPd+cZO4o+4RD5Q9YlfsEbeJGxA1"
    "zyGYyoJm3CYGnUMziz8c2jdGpexkM6ubi5zvUzDuAbEsiNG10bcrn4Fj/1Dm1T/gfgLgyP8+tBIsZggmF4xp9xXHuglml7VL"
    "5hBaOFbYJTvYfw0cJOlJiG8M/j0NtedButhMiOQ33kCS7+EP41kJr3x/FETnl0H6Cq56tiKWaou/C7aAHxxMDfR2HaMDdqtj"
    "9Ax3abdZ9xDzMnpgr9weox/CtGHmAJg3e+qadhuzKIA5bXRwnbZ46l3rwC9GP4R1dSzwlr0ew0wL8UOU2wNzAF7zDtjenmt2"
    "AQmw3Ga779kwHvhb+ilGhS7Xu6bTw1aYTQKmU/y6VgXaobG8Cg6IH8yi159aWIqi5QK6XZtwZr1rlWni16T6pu2+5Tg7BW/H"
    "einPF2vslz57662eQFCfQjr3RQ9EJ9tZrMb52S8FO0qGlCfj9JifvV5NpnGwTvcvHXoxu2H3b7ExO7nE+Gp4kn0mQrvoBF3T"
    "SV2GmjJrTU82k6H2N3UErun01WBrMdTk4TFgaRGef80DYkQCVvFDTTnExTJcfg+1v8yhpCSNDaTZcZgIGNlEqr/8gaGm00kf"
    "CuG8HjFcdxOpfvwTKEkZB4avOTmCwR2iyhOfDmGPsERFBRSJQXa0Ikd2YeSaQxFo7tLIP/LBB8IFfa8/u8DKg8OhtnUwgBW+"
    "Dfpe2XnHcppUsXctp9VeZIVi/xhatnHfFwSwZt9XdupAp+1dS+jaIVL8uNuOCBZFRMLNtuewmLbY8knJ7TSs2CmIf9ENIEEt"
    "ilCS4TuFsRMKBL+vZSJHkgWyJKeCD/j1xndPAcLMU+z/+Ydnfzz73fe/+uTPvz//EF4enX90/j/Z+QdnX5z/5rtPzj5hZ7+D"
    "so/PP2Rnn51/jI1yr3D26OwPZ59Bo0/PvmLQ+eOzT6V3OP8WXn8jy74DGF/Cw6Ozz9jZV2efIsRP2XcwIIPSr7Dm/H+ws0/P"
    "P8BB4B07fAGgPz37Hfv+/X8uiPL9+7+nzue/ISg4MkIwsZUgIrQAlM/fP/tXGhfKX30Le51/zM4eQfvPECj8/gNWvWgTQMLt"
    "z7+nWdCoX8JMPwISfPcJkOXsG5z82SPVyVCXb9jZPwGZAGrubIB0H5x/hLT8EMb4OpsMFn/3CUwOB4EW38LLx4AKDPfp2edE"
    "EmUwGAoId/YN0rZm+sAEAHj21Z8f4QCf4g9iA7x/CuVA4i9xJmefI/XLUAnfT5HDWIj0kXyCLn+EJn/EEmJZzickx9cwl/+T"
    "+zJADFn2p5IjUwF8nAuP8GbnHwGrP1SI8jkO/R1x6SvEXKBURRcl73NoDsCgzfmvgWYfAEbQcJsmFZnJpE11fpmkCeGrgsh9"
    "4DbsR8AmklVA9HeMsP0akEAwhF2Vwh/i/ARj85YwPaFIfyIEcLKZSADd3gdqUTPk6VeC/aRUX+OksHUmlbkKihZ/oClKF/r4"
    "CeYmjOaETEAun38oTNnZp3+mYokP2IBa1cM5o3ASf0D7QHqgHXhV0rL3z/6EjCfxyrUd0fqGpP/8Q9XrZvzKGwIuQN8viYfC"
    "0EgfvFWTsRwUCsX+g4vsBSgoiPlvhIgIPklXvbNT7rFRNEllP1J8NuCCQ6K5IvT/lHtspOk5ijrwW5o50VgWIQafgblFgX9f"
    "6Io0e+ffIu2/yXWTLE4uXZ+hTiLLc7nB0n9DlsMowLd/QZUHhZM+XmKoWkWGEkXDgAT9FucjHH42marFzPy+rN9hPPMoQNhk"
    "ZIxKbsHEPCoQcvcFti21KwUJpUYlgyVtUTloKFwMGsaiA2og6EceQQhLp3ogkGShSh+jkqF9QaEHMB+e/Tsam0KCkeg4OUTi"
    "80xQPxd0IeVGTgHzviTWQie0mF/JkTJrl/m3fzn7EmsBQ6kPWSyS44Q2gERC+NAPSBGyyKREX7RLCBrKUHlLccqFSv5PWCv4"
    "qIQupC7f4FzLqm4KK7ilWsIsCgX5UFCPzBSR4Y+Z8UIpxUlhJcjY+fty6kL6cRBJXskyEEXBQcVe5BGP8LzICPK9ENZkdg8e"
    "M33GUlXtsEohG1Z/S5SBQSEiunQ6ogXyzTGm448uzTYrugDM7jYPWidY44+buHp+5+a7Dx/ig8lXrVHMaYHhv3Pw7nPjMX7j"
    "GMNs/wUsGDZls2plUTw8aI1Oi7GStBn4+qEYj4/9aLpZ4h+DmfP0pZDj4y+Ob/jQpjUKZk3e4iZepbsu/wrQYQnU4mlBUcbG"
    "K3dfu1kBJO8XhHSX7OY4HCHEmTcOx2P60BV94S0Dnz3IMehTrtBlZz1+ZmLmvUBfmhhqYRqXwVWw1eR9Cq1l0rbHzQCWcOKO"
    "QlOLIPR9Dr9e/VgAeFNiBwDZHxih5RcMNP1uU8ueW60RkFaTVwg0vYnYl2LgmvsEwj7JZA1N7qQ87t4BDUV4gO0iHPB3K8cP"
    "8+RFsbXI2oqMeFkqm8vyCf7hCCrHJzkNmRwtK+hRGcDOBrCLAexiAFsZIEvWpRp6yYcQGaSyCz0qQzjZEE4xhFMM4ahzcIxQ"
    "loZKWT4vR84rA+1moN0CtFuAdlXQrnEkS4+UsoNDWQgPRalvy1J4KEpzNNwKGu0MjXaBhsiBksX0qHToZB06RYdOgXdHxVuk"
    "qcgKeixqyFfIKvGccaSjcKSjcAQVOwl22gqtdGtEE1+3nDXlpgpmoeyPLfb88wADfz6XBIqSyb+5lTQ1zNyCAenzoYnaW15K"
    "Pj6hXbA7MAbuH4H9uZHyZVPDYzED9VfTw9Yp4DBdgN06wVupubEq3Vci0zcd77Q9ML1raRoHk00K2l/8ZRKthZZN/HWSFzS8"
    "14SmiV53G7JkFzB92hrtpKgcr2TGp+ro3//2VzD497/9Vhs9hjL5aAppTi+RT0ugAx+fiF2qJd2nf+ddsWS4B3xZ8WnK/SGl"
    "O8pS/GDOEPoLnyi3sJLxO++S8ReA7mLekiYiB43KFV6OrdGlakrUWFP96k/Q95xk/vMC96Sw99AL1V4EwqTPcphA+mWz7EwX"
    "0VGTg9vioSKHMV9GhzyTQrU9lmy393y/rvEymTfpj6VNw0T62HD8k6aW3Y2C1gCmcKnY9gVN3bAHCEy70oT+Dx9qSG+tdUVr"
    "7GtXeDIl0PAqtvA1/AqtMjY2gEFB9Z5LWoIU0EDS5E6Kn6CCepgpJb82957fm+va895yPdKU0qtUGqalwn0qnJcLG1T43zYR"
    "Fo9K2uaBrUnV+VORmLwq0+lom6jIH2gJUnw3WPJokzYzwM0dPBM9TvFvwViVuAlNyUogIsLE8V109vgEY2DxAsVvFsVNfAlA"
    "PgORZ5yYIV/N08UouHJFmgzoHVxdgerjZtmwGYBCwhuEB8CI1mhxZaxVb9dlmcCVYmAwABNsbRLI5y/blmW5IwR7xW7lPN4C"
    "SLhhP4HkO8G7eVMhFKPTn2xZZEXgFiOS/+02JcLNo5TSB5F2ZdqMOwVBBGsRjnYlEPFi2Mo4hFuMYw1zcnGOglRAKJbpTMab"
    "kWodViNUIE2rIIN1FnA/RwvYTGr52GnIq3JFT7umgas2cFujMPL8O5v5nCf0oVQyH5e85Hg1ZXlPbx00lzxdRL6OZ6s6WnZB"
    "lWidjk9E1VC2wE8iwDJqeKJJwTfQSAI18E+BIeYAce9+ApJ0qk+96YIPwXYbZJ61U6QrQQfAJn5VYfxf7rx+y0xIoYPZsagk"
    "WY7HHkYNbMbR0hNe0EnU3SdHcV+2iE0cDmeWe4V0AXEsnei8FMfAc+3GCkxo4OPhwxrIQFxD4xKb0cHDh8/dh1+taqf7+M2y"
    "KAbT9crdu7dBzmNTXAPNl0T3a4gZ8xkMsrhDX8wCTABRQlkii7TWfvnSXVib7cHzHvimWYCmVDiw+0ghwKbstxSWOoKlcvub"
    "+FlMGwWOm/KrdLoG6OM8t3FU75gRdhDPofjnEW5rBCVm9t3TMR68U4lq75o35eLohfJWRnl1j5sY4vgBD0SUZTWUt0aPow4h"
    "tLeJIRgWhIHH1omak0xFRSIy6ZyC2dNuc8pdgCfa3cy3MbWtI0XuV88UYR5RHLzHS8eJUozoSEdr6dJFjtZRGErujE7BMGKn"
    "ijzfoq9waarMk7Wh6iHI6pYYlBhKcdAWR4tlDQlNLi4KPsSt4HCMcRl+pwejlbJwPYHMC64KXcoYq8j6NORenEMPDreYihvw"
    "KGnAq+c0Om0UXZ9DGkYoBRepCxGUxiT13jVeQUrZMCNkSU+qJC1X7iSuEr7qdgc9fX2IsI2aiAxEbFBV6/JM69lw+/U7OR+y"
    "mFfTT05bozwCvm9mjw8fymg4Ee6xuK5HQY0a/G0FHhmMrdAjKlYr4nRcBsNAnzVOA0BHIuAdZzAgMjADH4pVgqqVeFB7RWNN"
    "7Uq5i5mAS+JNS+9DFAImp6UR2vhh0pV/Hf+2QDMSnqCCLsia3TrBthVMLMKkxqtWFPFlL8BT7DQiruTLi1rVPK1nZWmAJ3ck"
    "JNpJ3lcE0cA85YqeJlcUrfrisdrfVBqAK9RGEpx6a06FV1deBqi2UCHKC20qsEpRGY6sJBCn5RVhhZrFFbSTXdJMa8DAH+cs"
    "J6w8XIlVrI88DBI+JD+Jqx7coFO4Iy66enmSSpaQ0co4LxzA6FSwdFuqcjvWJrujXl2rmJeKN6Y93/fPPittSn+NO9siwQ9c"
    "ofDML2N4JdMpsvN5+nuxsh256Xzo7CpcKQzXLrwWBxHzjkAB99M/xJ3qs0cClxejoxXSQKZTFOHBbIfMU2xoyOX5U1CoIIqC"
    "A/kT1gQSAcozEz9EtmdbThugRC/jdwgh3gYb8+ovgHYteVKw44wnTz7x5YzAEjQfAxVAlpJJfkyqZ6eqpXOy849LWQPZSdeZ"
    "OK2TQU5+SIQHkR+cfW1SxMTO/oAR0SM6TPo1Pv4b6YQ8xgPS4rnp/6aTHTz3xxZfiTPC34kUA/DaaPvLgkcZcSINTgZISZ5I"
    "w/PvjGK2VSA+Nop/XpphUgyml8Scs2Ww2qQ80fErpZTQViRpUVxmSk1fe8fIlmy/6B7eTxsWWz56YRqGYAJ0xQQO0RGXjebD"
    "h/mxh67aNtG0bA/VttJ+iWa5pVNanI4udN++THiRk2nRavgNukQIHkDcJlQDRHVZ+JhgsRT+KWBjBUqnNdra/YpNerwHMfnD"
    "h3HmOuhNE/tnt98umSoSKpCG25K5YBpv3yqpKh0OUgvMXGrpb79ap8m5yqk7IbSLIT5FKvecYtWb0caErCb1jE1FHADjzLBc"
    "0VpXJ/E+OSplhi2CjxVXbt+6og2LFNlssKLpFe1psmPr+mOurMSgIOvzz6tvz43H9ei9/WotekXPZ8SvBEBBcLMBv5kN/+ab"
    "N16EwfE7sHlHaoBdRKno5fmgvvdQzVXKvk2ol3orDasw/CiK7xUkIO/xolP1jpiFhaleH5CThsjJz5LZsr0vGvtFp5ZslTGe"
    "jXRbQAT5TmkWqs3IafHqW1U6qM1MOqtDNdumiX0vy2jMgb1oV4EprcwsrHoy8r5SUsjsjFvmIXyinHqTsqslIhcNV9J4eo1r"
    "66/y4/7i7F6wytw608ezd0zCKZ/hM5GbkqcMyISbD8BvfSEHFdEZZmInmJVK89Fz/5IlJMaUQ+1hBrciICa7IXJyKa9xRwok"
    "xC3C8USYjlqIlBSrVySbwXfDks8XZLzzVklKxSTyuaJLJvIViRqiwRdZkmAl3ULtKvOloPuXlI0j0g8IZp60ITMrBBFFfkt9"
    "upqZxwZEcwmckqREih6EGhgKyIQ7BWmR4fUI0P2S0nw+UrIl/wQP/1oEzrnnzgisfmgcU3BFIn1I2dRZG8oihyVlSq0pGTsl"
    "57VSEsthkW6ya/jn4TChNcvL1+nW2JyXAg0MKzCFP5oV2eYUGgerJPCztiA72yy+81axzxDjIda9DKhk9m2V2d//r//7//79"
    "vyNT8Qz9a0k0keqThV9CuCkDZ5v3FWGpzfyRjKjkp2YpVRCsUWAHmvZrPOXP229jQApMXvcP2O5rAZAStCjN8VE1mwtLMmnA"
    "QUXazBdyoXT2CCKQYUaDW1FBfuJnyo55ajLKXy5JBAgB8ZmaAHtAM99cpUHIvCoEnR0tIrrjACHndMFBUuRKrAgic14CMmj1"
    "qjYf85K9MMxCmWc0+ttQhNWvCM9tOvcoPgdROfSA2CxbGKWLcem4dF5zXEo7AumidfIM57rQ7ekOdmnnpO5k95SOreYXoUvn"
    "3oRtOG/lKTlzPGgTmtRceYfBHM9GKOdmAyCIjLCUuhkd8fg6+K5my6Td7eTtIF2ID4a2Sp8PHanH6uXN+hF++lleJLq6Jz/6"
    "vId/8m7/0v8Hk76K03iNAAA="
)
# --- END EMBEDDED UI ---


def ui_html() -> bytes:
    """The wizard page, from static/index.html if present, else from this file."""
    local = STATIC_DIR / "index.html"
    if local.exists():
        return local.read_bytes()
    if not _EMBEDDED_UI_B64:
        raise _CFErr("No UI available: static/index.html is missing and nothing is embedded.")
    import gzip as _gzip
    return _gzip.decompress(base64.b64decode(_EMBEDDED_UI_B64))
WORKER_FILE = BASE_DIR / "worker.js"
GITHUB_WORKER_URL = "https://raw.githubusercontent.com/IRNova/Nova-Proxy/refs/heads/main/worker.js"
# The exact release the Telegram bot deploys. Both tools install the same bytes or
# neither does: this tool downloads an executable over the network and hands it
# straight to the user's own Cloudflare account, so an unverified download is a
# supply-chain hole. Bump this together with the bot's WORKER_JS_SHA256.
WORKER_SHA256 = "c69c9b05b670c09083f5dd9c18c1d482173ef13fe493d712e367eb3e9c5ae010"
CF_API_BASE = "https://api.cloudflare.com/client/v4"
LOCAL_TOKEN = secrets.token_urlsafe(32)
COOKIE_NAME = "nova_token"

# The Nova mark, inlined so the callback page needs no network and no asset file.
NOVA_MARK_SVG = (
    '<svg width="48" height="48" viewBox="0 0 1254 1254" aria-hidden="true" focusable="false"> <defs><linearGradient id="cb-novaMark" x1="128.06" y1="1122.76" x2="1206.85" y2="43.97" gradientUnits="userSpaceOnUse"><stop offset=".04" stop-color="#9d4efb"/><stop offset="1" stop-color="#02cdf3"/></linearGradient></defs> <path fill="url(#cb-novaMark)" d="M1185.57,149.23c0-43.84-27.55-82.6-66.19-100.7-40.83-19.13-87.98-16.85-126.82,6.19-33.3,19.76-56.22,55.99-56.25,95.68l-.38,653.25.09,39.98c.03,13.51-.33,26.37-3.82,39.13-8.12,29.65-30.52,53.04-56.69,62.39-32.53,11.62-65.87,5.5-91.07-15.75-20.65-17.42-33.28-42.64-33.32-70.11l-.35-245.85.07-231.05c.04-148.83-97.26-281.46-240.38-321.81-67.49-19.02-138.62-19.66-204.99,2.42l-13.66,4.55C159.84,114.72,68.42,239.99,68.41,381.43l-.06,712.76c0,68.93,56.48,123.39,124.03,124.15,65.31.73,125.56-52.18,125.64-120.57l.88-712.63c.07-54.62,49.94-96.23,103.56-88.53,43.56,6.25,78.96,43.23,79.08,88.34l1.24,493.92c.16,62.52,24.72,123.29,59.49,174.21,43.7,63.99,108.48,111.28,182.25,133.98,91.72,28.23,190.9,16.68,273.4-31.79,36.89-21.68,68.83-50.13,94.95-83.49l16.54-23.16c31.76-44.47,56.26-119.27,56.25-174.93l-.09-724.43Z"/> </svg>'
)

# Nova's own Cloudflare OAuth client.
#
# This used to send Wrangler's client id, which works but is not ours: the consent
# screen said "Wrangler", so people were asked to trust a tool they had not downloaded,
# and Cloudflare could restrict that client at any time without warning.
OAUTH_CLIENT_ID = "64171e17a3242d9f2385c9a8f4f7381f"
OAUTH_AUTH_URL = "https://dash.cloudflare.com/oauth2/auth"
OAUTH_TOKEN_URL = "https://dash.cloudflare.com/oauth2/token"
OAUTH_REVOKE_URL = "https://dash.cloudflare.com/oauth2/revoke"
# Third-party OAuth clients use a different scope namespace from Wrangler's. These are
# the ids registered on the client above, verified against GET /client/v4/oauth/scopes.
#
# page.read is here because the deploy path does a GET on pages/projects before it
# creates one. zone:read is gone: nothing in this file calls /zones, so it was asking
# people for access it never used.
OAUTH_SCOPES = [
    "workers-scripts.write",     # upload the panel worker
    "workers-kv-storage.write",  # its KV namespace
    "d1.write",                  # its database
    "page.write",                # the pages.dev second address
    "page.read",                 # check whether that project already exists
    "memberships.read",          # list the accounts the user can deploy into
    "user-details.read",
]
OAUTH_REDIRECT_PORT = 8976

_oauth_state = ""
_oauth_code_verifier = ""
_oauth_token = None
_oauth_account_id = ""
_oauth_account_name = ""
_deployment_history: list = []

# ─── helpers ───────────────────────────────────────────────

def dumps(d): return json.dumps(d, ensure_ascii=False, separators=(",",":")).encode("utf-8")
def read_json(h):
    l = int(h.headers.get("Content-Length") or "0")
    r = h.rfile.read(l) if l else b"{}"
    return json.loads(r.decode("utf-8")) if r else {}

def safe_name(v, fallback="nova-panel"):
    c = "".join(ch.lower() if ch.isalnum() else "-" for ch in (v or "").strip())
    while "--" in c: c = c.replace("--", "-")
    return c.strip("-") or fallback

_WORDS_A = ["sunny","nova","swift","neon","atlas","orbit","pixel","rocket","falcon","crystal","rainbow","mango","coral","luna","pearl","turbo"]
_WORDS_B = ["panel","bridge","node","core","wave","path","gate","proxy","stack","vault","spark","portal","cloud","river","garden","comet"]
_STORE_WORDS = ["vault","store","cache","locker","garden","stash","bucket","shelf"]

def fetch_worker_from_github():
    print("  [fetch] Downloading worker.js from GitHub...")
    try:
        with urlrequest.urlopen(urlrequest.Request(GITHUB_WORKER_URL,
            headers={"User-Agent":"Mozilla/5.0"}), timeout=30) as r:
            code = r.read()
            if len(code) < 100: raise _CFErr(f"Downloaded file too small ({len(code)} bytes)")
            got = hashlib.sha256(code).hexdigest()
            if got != WORKER_SHA256:
                # Fail closed. Nothing is written, so a later run cannot pick up a
                # rejected file that happens to be sitting on disk.
                raise _CFErr(
                    "worker.js does not match the expected release.\n"
                    f"  expected {WORKER_SHA256}\n  got      {got}\n"
                    "Refusing to deploy it. If Nova has published a new release, update "
                    "WORKER_SHA256 in this file to the new digest.")
            WORKER_FILE.write_bytes(code)
            print(f"  [fetch] OK, {len(code)} bytes saved, sha256 verified")
            return len(code)
    except urlerror.HTTPError as e:
        raw = e.read()
        raise _CFErr(f"GitHub HTTP {e.code}: {raw.decode('utf-8','replace')[:200]}")
    except Exception as e:
        raise _CFErr(f"GitHub fetch failed: {e}")

def rand_name(max_len=55):
    for _ in range(50):
        s = f"{secrets.choice(_WORDS_A)}-{secrets.choice(_WORDS_B)}-{secrets.choice(_WORDS_A)}-{secrets.token_hex(3)}"
        s = safe_name(s, "nova-panel")[:max_len].strip("-")
        if s: return s
    return f"nova-panel-{secrets.token_hex(4)}"[:max_len]

def suggest():
    w = rand_name(55)
    kv = safe_name(f"{w}-{secrets.choice(_STORE_WORDS)}", "nova-panel-vault")[:60].strip("-") or f"nova-{secrets.token_hex(4)}-vault"[:60]
    d1 = safe_name(f"{w}-db", "nova-panel-db")[:32].strip("-") or f"nova-db-{secrets.token_hex(4)}"[:32]
    return {"worker_name": w, "kv_namespace": kv, "d1_name": d1}

# ─── OAuth PKCE ────────────────────────────────────────────

def gen_state(): return base64.urlsafe_b64encode(secrets.token_bytes(32)).decode().rstrip("=")
def gen_verifier(): return base64.urlsafe_b64encode(secrets.token_bytes(33)).decode().rstrip("=")
def gen_challenge(v): return base64.urlsafe_b64encode(hashlib.sha256(v.encode()).digest()).decode().rstrip("=")

def oauth_url():
    global _oauth_state, _oauth_code_verifier
    _oauth_state = gen_state()
    _oauth_code_verifier = gen_verifier()
    p = urlencode({"client_id": OAUTH_CLIENT_ID, "response_type": "code",
        "redirect_uri": f"http://localhost:{OAUTH_REDIRECT_PORT}/oauth/callback",
        "scope": " ".join(OAUTH_SCOPES), "state": _oauth_state,
        "code_challenge": gen_challenge(_oauth_code_verifier), "code_challenge_method": "S256"})
    return OAUTH_AUTH_URL + "?" + p

def _make_ssl_ctx():
    """A verified TLS context, with certifi's CA bundle if this machine has one.

    There is no unverified variant on purpose. The token exchange carries the
    authorization code AND the PKCE verifier, which together are enough for anyone
    holding them to mint a token on the user's Cloudflare account. Most of this tool's
    users are on networks where TLS interception is routine, so retrying that request
    without verification would hand an interceptor both halves. A missing CA bundle is
    a machine problem with a real fix, printed below, not a reason to drop verification.
    """
    try:
        import certifi  # not a dependency; used only when the machine already has it
        return ssl.create_default_context(cafile=certifi.where())
    except Exception:
        return ssl.create_default_context()

_OAUTH_OPENER = urlrequest.build_opener(urlrequest.HTTPSHandler(context=_make_ssl_ctx()))

CERT_HELP = (
    "TLS certificates could not be verified on this machine, so the sign-in was stopped.\n"
    "  This is a certificate store problem, not a Cloudflare problem.\n"
    "  On Windows:  py -m pip install --upgrade certifi\n"
    "  On macOS:    run 'Install Certificates.command' inside your Python folder\n"
    "  Then start the wizard again."
)

def revoke_oauth_token():
    """Hand the grant back when the tool exits.

    Without this the access token stays usable on the owner's Cloudflare account for its
    full lifetime after the window is closed, which is a credential outliving the thing
    that needed it. Best effort and silent on failure: a revoke that does not land is not
    a reason to fail a deploy that already succeeded.
    """
    global _oauth_token
    if not _oauth_token:
        return
    try:
        d = urlencode({"token": _oauth_token, "client_id": OAUTH_CLIENT_ID}).encode()
        req = urlrequest.Request(OAUTH_REVOKE_URL, data=d,
            headers={"Content-Type": "application/x-www-form-urlencoded"})
        with _OAUTH_OPENER.open(req, timeout=10):
            pass
        print("  Cloudflare access handed back.")
    except Exception:
        pass
    finally:
        _oauth_token = None

def exchange_token(code, verifier):
    d = urlencode({"client_id": OAUTH_CLIENT_ID, "code": code, "code_verifier": verifier,
        "redirect_uri": f"http://localhost:{OAUTH_REDIRECT_PORT}/oauth/callback",
        "grant_type": "authorization_code"}).encode()
    req = urlrequest.Request(OAUTH_TOKEN_URL, data=d,
        headers={"Content-Type":"application/x-www-form-urlencoded","Accept":"application/json","User-Agent":"Mozilla/5.0"})
    try:
        with _OAUTH_OPENER.open(req, timeout=30) as r:
            return json.loads(r.read())
    except urlerror.URLError as e:
        # A TLS failure here STOPS the exchange. It is never retried unverified: this
        # request carries the code and the verifier together.
        if isinstance(getattr(e, "reason", None), ssl.SSLError) or "CERTIFICATE" in str(getattr(e, "reason", "")).upper():
            print("  [stop] " + CERT_HELP)
            raise _CFErr("TLS verification failed, so sign-in was stopped. See the message above.")
        raise _CFErr(f"Token exchange network error: {getattr(e,'reason',e)}")
    except urlerror.HTTPError as e:
        raw = e.read()
        try: body = json.loads(raw)
        except: body = raw.decode("utf-8","replace")
        print(f"  [OAuth token exchange HTTP {e.code}] {body}")
        raise _CFErr(f"Token exchange failed (HTTP {e.code}): {body}", status=e.code)
    except Exception as e:
        import traceback as _tb
        _tb.print_exc()
        print(f"  [OAuth token exchange error] type={type(e).__name__} repr={repr(e)}")
        raise _CFErr(f"Token exchange failed ({type(e).__name__}): {repr(e)}")

# ─── OAuth callback server (port 8976) ─────────────────────

_oauth_result: Dict = {}
_oauth_error: str = ""
_oauth_event = threading.Event()
_oauth_processed_states: set = set()

class OAuthCBHandler(BaseHTTPRequestHandler):
    def do_GET(self):
        global _oauth_state, _oauth_code_verifier, _oauth_result, _oauth_token, _oauth_account_id, _oauth_account_name
        p = urlparse(self.path)
        if p.path == "/oauth/callback":
            q = parse_qs(p.query)
            code = (q.get("code") or [None])[0]
            state = (q.get("state") or [None])[0]
            err = (q.get("error") or [None])[0]
            # If already connected, return success (handles duplicate callbacks)
            if _oauth_token and state in _oauth_processed_states:
                ok = True; msg = "Already connected - close this tab"
            elif err:
                _oauth_error = f"Cloudflare: {err}"; _oauth_result = {"ok": False, "error": _oauth_error}
                ok = False; msg = _oauth_error
            elif not code or state != _oauth_state:
                _oauth_error = "Invalid state"; _oauth_result = {"ok": False, "error": _oauth_error}
                ok = False; msg = _oauth_error
            else:
                _oauth_processed_states.add(state)
                try:
                    t = exchange_token(code, _oauth_code_verifier)
                    if t and t.get("access_token"):
                        _oauth_token = t["access_token"]
                        _oauth_error = ""
                        _oauth_result = {"ok": True, "access_token": t["access_token"], "refresh_token": t.get("refresh_token","")}
                        # Fetch the first account so the UI can show whose account this is.
                        try:
                            _acc = CFClient(_oauth_token).req("GET", "/accounts?per_page=1")
                            _first = (_acc.get("result") or [{}])[0]
                            _oauth_account_id = _first.get("id") or ""
                            _oauth_account_name = _first.get("name") or ""
                        except Exception: pass
                        ok = True; msg = "Connected - close this tab"
                    else:
                        _oauth_error = f"Token failed: {t.get('error_description',t.get('error','?')) if t else 'no response'}"
                        _oauth_result = {"ok": False, "error": _oauth_error}
                        ok = False; msg = _oauth_error
                except _CFErr as e:
                    _oauth_error = str(e)
                    _oauth_result = {"ok": False, "error": _oauth_error}
                    ok = False; msg = _oauth_error
            # Bilingual (EN + FA) callback page. Built without backslashes inside f-string
            # expressions (that pattern raises SyntaxError on Python <= 3.11). IRNova brand.
            icon = "&#9989;" if ok else "&#10060;"
            if ok:
                en_status = "Connected"
                fa_status = "وصل شد"  # وصل شد
                en_hint = "This window can be closed. The wizard continues automatically, so switch back to it."
                fa_hint = ("این پنجره را می‌توانی "
                           "ببندی. دستیار خودکار "
                           "ادامه می‌دهد، به آن برگرد.")  # close window / wizard continues
                extra_html = ('<p style="color:#9aa4b8;margin-top:12px;font-size:.95rem">' + en_hint + '</p>'
                              '<p style="color:#9aa4b8;margin-top:4px;font-size:.95rem" dir="rtl">' + fa_hint + '</p>')
            else:
                en_status = "Sign-in failed"
                fa_status = "ورود ناموفق بود"  # ورود ناموفق بود
                btn_label = "Try again / دوباره"  # Try again / dobare
                extra_html = ('<p style="color:#fca5a5;margin:8px 0 0;font-size:.9rem">' + msg + '</p>'
                              '<button onclick="window.close();if(window.opener)window.opener.location.reload()" '
                              'style="padding:11px 24px;border-radius:12px;border:none;'
                              'background:linear-gradient(120deg,#22d3ee,#818cf8,#a855f7);color:#05060a;'
                              'font-weight:700;font-size:14px;cursor:pointer;margin-top:14px">' + btn_label + '</button>')
            html = (
                '<!doctype html><html lang="en"><head><meta charset="utf-8">'
                '<meta name="viewport" content="width=device-width,initial-scale=1"><title>Nova</title>'
                '<body style="margin:0;background:#05060a;color:#eef1f7;'
                'font-family:Vazirmatn,system-ui,-apple-system,Segoe UI,Roboto,sans-serif;'
                'display:grid;place-items:center;min-height:100vh">'
                '<div style="text-align:center;padding:36px;max-width:440px">'
                # The real Nova mark, the same inlined SVG the wizard UI uses, rather than a
                # gradient tile with a letter in it.
                '<div style="margin:0 auto 18px;width:48px;height:48px">' + NOVA_MARK_SVG + '</div>'
                '<h1 style="font-size:1.4rem;font-weight:800;margin:0 0 14px">Nova Wizard</h1>'
                '<p style="font-size:1.1rem;margin:0;font-weight:600">' + icon + ' ' + en_status
                + ' <span style="color:#9aa4b8">/</span> ' + fa_status + '</p>'
                + extra_html +
                '</div></body></html>'
            )
            self.send_response(200)
            self.send_header("Content-Type","text/html; charset=utf-8")
            self.send_header("Content-Length",str(len(html.encode())))
            self.end_headers(); self.wfile.write(html.encode())
            _oauth_event.set()
        else:
            self.send_response(404); self.end_headers()
    def log_message(self, *a): pass

def start_oauth_server():
    s = ThreadingHTTPServer(("127.0.0.1", OAUTH_REDIRECT_PORT), OAuthCBHandler)
    threading.Thread(target=s.serve_forever, daemon=True).start()

# ─── CF API ────────────────────────────────────────────────

class CFClient:
    def __init__(self, token, timeout=70):
        self.token = token; self.timeout = timeout
        self.opener = urlrequest.build_opener()
    def req(self, method, path, *, json_body=None, data=None, ctype=None, extra_headers=None, accept_404=False):
        h = {"Authorization": f"Bearer {self.token}", "Accept": "application/json", "User-Agent": "nova-wizard/3.0"}
        if extra_headers: h.update(extra_headers)
        if json_body: data = dumps(json_body); h["Content-Type"] = "application/json"
        elif ctype: h["Content-Type"] = ctype
        r = urlrequest.Request(CF_API_BASE + path, data=data, headers=h, method=method.upper())
        try:
            with self.opener.open(r, timeout=self.timeout) as resp:
                raw = resp.read()
                p = json.loads(raw.decode("utf-8")) if raw else {"success": True, "result": None}
                if isinstance(p, dict) and p.get("success") is False:
                    raise _CFErr(format_err(p), status=resp.status)
                return p
        except urlerror.HTTPError as e:
            if accept_404 and e.code == 404: return {"success": True, "result": None}
            raw = e.read()
            try: p = json.loads(raw.decode("utf-8")) if raw else None
            except: p = raw.decode("utf-8","replace") if raw else None
            raise _CFErr(format_err(p) if p else f"HTTP {e.code}", status=e.code)
        except urlerror.URLError as e: raise _CFErr(f"Network: {e.reason}")

class _CFErr(RuntimeError):
    def __init__(self, msg, status=None): super().__init__(msg); self.status = status

def format_err(p):
    if isinstance(p, dict):
        es = p.get("errors") or []
        ms = []
        for e in es:
            if isinstance(e, dict): ms.append(f"[{e.get('code')}] {e.get('message')}" if e.get('code') else str(e.get('message')))
            else: ms.append(str(e))
        if ms: return "CF: " + " | ".join(ms)
        if p.get("message"): return str(p["message"])
    return str(p)

# ─── resource ops ──────────────────────────────────────────

def list_ns(cf, aid):
    out = []; page = 1
    while True:
        p = cf.req("GET", f"/accounts/{quote(aid)}/storage/kv/namespaces?per_page=100&page={page}")
        out.extend(p.get("result") or [])
        info = p.get("result_info") or {}
        if page >= int(info.get("total_pages") or 1): return out
        page += 1

def find_kv(cf, aid, title):
    for ns in list_ns(cf, aid):
        if ns.get("title") == title: return ns
    return None

def get_or_create_kv(cf, aid, title):
    ex = find_kv(cf, aid, title)
    if ex: return {"id": ex["id"], "title": title, "reused": True}
    p = cf.req("POST", f"/accounts/{quote(aid)}/storage/kv/namespaces", json_body={"title": title})
    r = p.get("result") or {}
    return {"id": r.get("id"), "title": r.get("title") or title, "reused": False}

def get_or_create_d1(cf, aid, name):
    try:
        p = cf.req("GET", f"/accounts/{quote(aid)}/d1/database?name={quote(name)}")
        rs = p.get("result") or []
        if rs: return {"id": rs[0].get("uuid") or rs[0].get("id"), "name": rs[0].get("name") or name, "reused": True}
    except: pass
    p = cf.req("POST", f"/accounts/{quote(aid)}/d1/database", json_body={"name": name})
    r = p.get("result") or {}
    return {"id": r.get("uuid") or r.get("id"), "name": r.get("name") or name, "reused": False}

def get_subdomain(cf, aid):
    try:
        p = cf.req("GET", f"/accounts/{quote(aid)}/workers/subdomain")
        r = p.get("result") or {}
        s = r.get("subdomain") or r.get("name")
        if s: return s
    except: pass
    des = safe_name(f"nova-{secrets.token_hex(4)}", "nova-panel")
    for m in ("PUT","POST","PATCH"):
        try:
            p = cf.req(m, f"/accounts/{quote(aid)}/workers/subdomain", json_body={"subdomain": des})
            r = p.get("result") or {}
            return r.get("subdomain") or des
        except: pass
    raise _CFErr("Could not set workers.dev subdomain")

def enable_subdomain(cf, aid, name):
    for m in ("POST","PUT","PATCH"):
        try:
            cf.req(m, f"/accounts/{quote(aid)}/workers/scripts/{quote(name)}/subdomain", json_body={"enabled": True})
            return
        except: pass
    cf.req("GET", f"/accounts/{quote(aid)}/workers/scripts/{quote(name)}")  # check exists
    raise _CFErr("Worker uploaded but subdomain enable failed")

def build_multi(meta, code):
    bound = "----wiz" + secrets.token_hex(16)
    nl = "\r\n"
    parts = []
    for key, fname, ct, data in [("metadata", None, "application/json", dumps(meta)), ("worker.js", "worker.js", "application/javascript+module", code)]:
        d = f'Content-Disposition: form-data; name="{key}"'
        if fname: d += f'; filename="{fname}"'
        parts.append(f"--{bound}{nl}{d}{nl}Content-Type: {ct}{nl}{nl}".encode("utf-8") + data + nl.encode("utf-8"))
    parts.append(f"--{bound}--{nl}".encode("utf-8"))
    return b"".join(parts), f"multipart/form-data; boundary={bound}"

def build_pages_multi(code):
    bound = "----wiz" + secrets.token_hex(16)
    nl = "\r\n"
    parts = []
    for key, fname, ct, data in [("manifest", None, "application/json", b"{}"), ("_worker.js", "_worker.js", "application/javascript", code)]:
        d = f'Content-Disposition: form-data; name="{key}"'
        if fname: d += f'; filename="{fname}"'
        parts.append(f"--{bound}{nl}{d}{nl}Content-Type: {ct}{nl}{nl}".encode("utf-8") + data + nl.encode("utf-8"))
    parts.append(f"--{bound}--{nl}".encode("utf-8"))
    return b"".join(parts), f"multipart/form-data; boundary={bound}"

# ─── deploy ────────────────────────────────────────────────

def rand_hex(n_bytes=6):
    """A secret path segment. Same shape and length the Telegram bot uses."""
    return secrets.token_hex(n_bytes)


def rand_password(length=18):
    """A strong admin password with the ambiguous glyphs (0/O, 1/l/I) left out,
    because people read this one off a screen and type it somewhere else."""
    alphabet = "ABCDEFGHJKMNPQRSTUVWXYZabcdefghijkmnpqrstuvwxyz23456789"
    return "".join(secrets.choice(alphabet) for _ in range(length))


# Cloudflare answers Python's default urllib User-Agent with 403 error code 1010,
# a browser-signature block, before the request ever reaches the panel. Every claim
# failed on it and the failure was swallowed, which is why three separate diagnoses
# blamed DNS and propagation instead. curl succeeded against the same endpoint the
# whole time, which should have been the clue.
BROWSER_UA = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0 Safari/537.36"


def claim_panel(panel_urls, password, attempts=30, delay=6):
    """Set the admin password ourselves, as soon as the panel answers.

    The shipped artifact has no claim-token gate, so between deploy and someone
    setting a password, /install/set is open to whoever reaches it first. That is
    not a small window on a public workers.dev hostname. The Telegram bot closes
    it by claiming immediately, and this does the same.

    Three minutes, because that is how long Cloudflare takes to bring a new address
    up worldwide and it is the figure Nova's own install message quotes. Sixty seconds
    was not enough: watched live on 2026-09-14, a brand-new account's workers.dev
    subdomain did not resolve at all inside the first minute, so every attempt was
    posting at a hostname that did not exist yet and the panel was handed over
    unclaimed. A fresh account is the worst case, because the subdomain has to be
    created before anything can answer on it.

    Takes every address the panel answers on and tries each one per round, because
    the panel keeps its password in the shared D1 store: claiming on either address
    claims both. A brand-new account's workers.dev subdomain has to be created before
    it resolves, while the Pages hostname comes up on its own timeline, so racing them
    claims through whichever is ready first instead of waiting on a fixed guess.

    Returns the address that accepted the password, or "" if none did."""
    if isinstance(panel_urls, str):
        panel_urls = [panel_urls]
    targets = [u.rstrip("/") + "/install/set" for u in panel_urls if u]
    body = json.dumps({"password": password}).encode()
    # Every attempt reports why it failed. The first version swallowed all of them,
    # which made a failed claim indistinguishable from a panel that refused, a
    # hostname that would not resolve, and a TLS error, and three separate diagnoses
    # were made from guesses because of it.
    seen = {}
    for attempt in range(1, attempts + 1):
        for url in targets:
            host = urlparse(url).hostname or url
            try:
                req = urlrequest.Request(url, data=body, method="POST",
                                         headers={"Content-Type": "application/json",
                                                  "User-Agent": BROWSER_UA})
                with urlrequest.urlopen(req, timeout=10, context=_make_ssl_ctx()) as r:
                    if 200 <= r.status < 300:
                        print(f"  [claim] {host}: claimed on attempt {attempt}")
                        return url[: -len("/install/set")]
                    why = f"HTTP {r.status}"
            except urlerror.HTTPError as e:
                detail = ""
                try: detail = e.read(120).decode("utf-8", "replace").strip()
                except Exception: pass
                why = f"HTTP {e.code} {detail}"
            except Exception as e:
                why = f"{type(e).__name__}: {e}"
            # One line per DISTINCT reason per host, so a three minute wait does not
            # print sixty identical lines, and a reason that changes is visible.
            if seen.get(host) != why:
                seen[host] = why
                print(f"  [claim] {host}: {why}")
        time.sleep(delay)
    print(f"  [claim] gave up after {attempts * delay}s")
    return ""


def deploy(cf, aid, worker_name, kv_title, d1_name, extra_env, deploy_type, paths=None):
    kv = get_or_create_kv(cf, aid, kv_title)
    kv_id = kv.get("id")
    if not kv_id: raise _CFErr("KV namespace ID not found")

    d1_db = None; d1_id = None
    if d1_name:
        d1_db = get_or_create_d1(cf, aid, d1_name)
        d1_id = d1_db.get("id")

    # Secret paths, the same shape the Telegram bot uses.
    #
    # Left unset, the panel answers on /admin and /login, which anyone scanning
    # workers.dev can find. The shipped artifact reads ADMIN_PATH, LOGIN_PATH,
    # WS_PATH and SUB_PATH, so there is no reason to hand out the default ones.
    #
    # ADMIN/KEY/UUID stay unset on purpose: the worker treats an env ADMIN as an
    # already-configured password and would skip /install entirely. The password
    # is claimed over HTTP right after deploy instead, see claim_panel.
    # A second door must answer on the SAME secret paths and the same UUID as the
    # Worker, or it is a different panel wearing the same database.
    paths = paths or {}
    ws_path = paths.get("ws") or rand_hex(6)
    admin_path = paths.get("admin") or rand_hex(6)
    login_path = paths.get("login") or rand_hex(6)
    sub_path = paths.get("sub") or rand_hex(6)
    panel_uuid = paths.get("uuid") or str(uuid_mod.uuid4())
    bindings = [
        {"type": "kv_namespace", "name": "KV", "namespace_id": kv_id},
        {"type": "plain_text", "name": "WS_PATH", "text": ws_path},
        {"type": "plain_text", "name": "PATH", "text": "/" + ws_path},
        {"type": "plain_text", "name": "ADMIN_PATH", "text": admin_path},
        {"type": "plain_text", "name": "LOGIN_PATH", "text": login_path},
        {"type": "plain_text", "name": "SUB_PATH", "text": sub_path},
        {"type": "plain_text", "name": "UUID", "text": panel_uuid},
    ]
    if d1_id: bindings.append({"type": "d1", "name": "DB", "database_id": d1_id})
    for k, v in extra_env.items():
        if v: bindings.append({"type": "plain_text", "name": k, "text": v})

    # global_fetch_strictly_public lets backend mode reach a same-account gray-cloud VPS hostname
    # without Cloudflare returning 522 (self-loop). nodejs_compat is required by the worker.
    meta = {"main_module": "worker.js", "compatibility_date": "2026-07-31",
            "compatibility_flags": ["nodejs_compat", "global_fetch_strictly_public"], "bindings": bindings}
    code = WORKER_FILE.read_bytes()

    if deploy_type == "pages":
        body, ct = build_pages_multi(code)
        try:
            ex = cf.req("GET", f"/accounts/{quote(aid)}/pages/projects/{quote(worker_name)}", accept_404=True)
            kv_ns = {"KV": {"namespace_id": kv_id}}
            d1_b = {}
            # The shape the Telegram bot uses, which has built 1,769 working doors.
            # Cloudflare does not reject the other spelling, it just ignores it.
            if d1_id: d1_b = {"DB": {"id": d1_id}}
            # The same secret paths as the Workers branch; a Pages door that answered
            # on /admin would undo the point of setting them at all.
            ev = {
                "WS_PATH": {"type": "plain_text", "value": ws_path},
                "PATH": {"type": "plain_text", "value": "/" + ws_path},
                "ADMIN_PATH": {"type": "plain_text", "value": admin_path},
                "LOGIN_PATH": {"type": "plain_text", "value": login_path},
                "SUB_PATH": {"type": "plain_text", "value": sub_path},
                "UUID": {"type": "plain_text", "value": panel_uuid},
            }
            for k, v in extra_env.items():
                if v: ev[k] = {"type":"plain_text","value":v}
            # Bindings belong under deployment_configs.production, not at the top
            # level. Cloudflare accepts the flat form and silently ignores it, so the
            # project came up with no KV and no D1 and the panel answered
            # {"error":"no_kv"} on every request. Confirmed live on 2026-09-14: the door
            # deployed, resolved, served a redirect, and could not be claimed. The
            # Telegram bot has always nested them, which is why its doors work.
            production = {
                "compatibility_date": "2026-07-31",
                "compatibility_flags": ["nodejs_compat", "global_fetch_strictly_public"],
                "kv_namespaces": kv_ns,
                "env_vars": ev,
            }
            if d1_b: production["d1_databases"] = d1_b
            proj = {"name": worker_name, "production_branch": "main",
                    "deployment_configs": {"production": production}}
            if ex and ex.get("result"):
                cf.req("PATCH", f"/accounts/{quote(aid)}/pages/projects/{quote(worker_name)}", json_body=proj)
            else:
                cf.req("POST", f"/accounts/{quote(aid)}/pages/projects", json_body=proj)
        except _CFErr as e:
            if e.status == 404: cf.req("POST", f"/accounts/{quote(aid)}/pages/projects", json_body=proj)
            else: raise
        cf.req("POST", f"/accounts/{quote(aid)}/pages/projects/{quote(worker_name)}/deployments", data=body, ctype=ct)
        sub = None
        try:
            pj = cf.req("GET", f"/accounts/{quote(aid)}/pages/projects/{quote(worker_name)}")
            sub = (pj.get("result") or {}).get("subdomain")
        except: pass
        # The project's Pages hostname is simply <project>.pages.dev, which is what the
        # Telegram bot uses for its doors. The API's `subdomain` field already IS that
        # full hostname, so prefixing the project name again produced
        # <name>.<name>.pages.dev and every claim through the door failed DNS.
        url = f"https://{sub}" if sub and sub.startswith(worker_name + ".") else f"https://{worker_name}.pages.dev"
    else:
        body, ct = build_multi(meta, code)
        cf.req("PUT", f"/accounts/{quote(aid)}/workers/scripts/{quote(worker_name)}", data=body, ctype=ct)
        enable_subdomain(cf, aid, worker_name)
        asub = get_subdomain(cf, aid)
        url = f"https://{worker_name}.{asub}.workers.dev" if asub else ""

    # Claim the panel before handing it over.
    #
    # /install/set is open until somebody sets a password, so a panel left unclaimed
    # belongs to whoever reaches it first. We set a strong one now and show it to the
    # owner, who can change it from inside the panel. Same order the Telegram bot uses.
    # The claim is the caller's job now. It owns both addresses and can race them,
    # which this function cannot see from inside a single deploy.
    password, claimed = "", False

    return {"worker_name": worker_name, "worker_url": url,
        # The secret login path, not /login. /login and /admin serve a decoy.
        "panel_url": f"{url}/{login_path}" if url else "",
        "login_path": login_path, "admin_path": admin_path,
        "admin_pass": password if claimed else "",
        "claimed": claimed,
        # Only true when we could NOT claim it, in which case the owner has to set
        # the password themselves, immediately, at /install.
        "set_password": not claimed,
        "install_url": f"{url}/install" if url else "",
        "kv_namespace": kv, "d1_database": d1_db, "deploy_type": deploy_type,
        "paths": {"ws": ws_path, "admin": admin_path, "login": login_path,
                  "sub": sub_path, "uuid": panel_uuid},
        "kv_id": kv_id, "d1_id": d1_id}

def report_install(worker_url):
    """Tell novaproxy.online's counter about a real deploy, in the background.

    The id is a hash of the panel host, matching the web installer and the
    Telegram bot, so one panel is tallied once across every deploy channel. The
    server only ever sees the opaque hash, never the worker URL. Runs in a daemon
    thread with a short timeout so it never delays or blocks the deploy result."""
    host = (urlparse(worker_url).hostname or "").strip()
    if not host:
        return
    def _send():
        try:
            wid = "w_" + hashlib.sha256(("nova-panel:" + host).encode()).hexdigest()[:32]
            data = json.dumps({"type": "install", "id": wid}).encode()
            req = urlrequest.Request("https://novaproxy.online/api/stats", data=data,
                headers={"Content-Type": "application/json"}, method="POST")
            urlrequest.urlopen(req, timeout=6).read()
        except Exception:
            pass
    threading.Thread(target=_send, daemon=True).start()

def cleanup(cf, aid, worker_name, kv_id, kv_title, d1_id, deploy_type):
    r = {"worker": False, "kv": False, "d1": False, "notes": []}
    if worker_name:
        try:
            if deploy_type == "pages":
                cf.req("DELETE", f"/accounts/{quote(aid)}/pages/projects/{quote(worker_name)}", accept_404=True)
            else: cf.req("DELETE", f"/accounts/{quote(aid)}/workers/scripts/{quote(worker_name)}", accept_404=True)
            r["worker"] = True
        except _CFErr as e:
            if e.status == 404: r["notes"].append("Worker not found")
            else: raise
    if not kv_id and kv_title:
        ns = find_kv(cf, aid, kv_title)
        if ns: kv_id = ns.get("id") or ""
    if kv_id:
        try: cf.req("DELETE", f"/accounts/{quote(aid)}/storage/kv/namespaces/{quote(kv_id)}", accept_404=True); r["kv"] = True
        except _CFErr as e:
            if e.status == 404: r["notes"].append("KV not found")
            else: raise
    if d1_id:
        try: cf.req("DELETE", f"/accounts/{quote(aid)}/d1/database/{quote(d1_id)}", accept_404=True); r["d1"] = True
        except _CFErr as e:
            if e.status == 404: r["notes"].append("D1 not found")
            else: raise
    return r

# ─── HTTP handler ──────────────────────────────────────────

class Handler(BaseHTTPRequestHandler):
    server_version = "NovaWizard/3.0"

    def authed(self, parsed=None):
        if parsed:
            qt = (parse_qs(parsed.query).get("token") or [""])[0]
            if secrets.compare_digest(qt, LOCAL_TOKEN): return True
        for part in (self.headers.get("Cookie") or "").split(";"):
            if "=" in part:
                k, v = part.strip().split("=", 1)
                if k == COOKIE_NAME and secrets.compare_digest(v, LOCAL_TOKEN): return True
        return False

    def send_json(self, data, status=200):
        raw = dumps(data)
        self.send_response(status)
        self.send_header("Content-Type","application/json; charset=utf-8")
        self.send_header("Cache-Control","no-store")
        self.send_header("Content-Length",str(len(raw)))
        self.end_headers(); self.wfile.write(raw)

    def send_html(self, html, status=200):
        raw = html.encode("utf-8")
        self.send_response(status)
        self.send_header("Content-Type","text/html; charset=utf-8")
        self.send_header("Cache-Control","no-store")
        self.send_header("Content-Length",str(len(raw)))
        self.end_headers(); self.wfile.write(raw)

    def send_file(self, path, set_cookie=False):
        if not path.exists() or not path.is_file(): return self.send_error(404)
        raw = path.read_bytes()
        self.send_response(200)
        self.send_header("Content-Type", mimetypes.guess_type(str(path))[0] or "application/octet-stream")
        self.send_header("Cache-Control","no-store")
        if set_cookie: self.send_header("Set-Cookie", f"{COOKIE_NAME}={LOCAL_TOKEN}; Path=/; SameSite=Strict")
        self.send_header("Content-Length",str(len(raw)))
        self.end_headers(); self.wfile.write(raw)

    def unauth(self):
        # Bilingual (EN + FA), IRNova brand. Shown if the page is opened without the secure token.
        page = (
            '<!doctype html><html lang="en"><head><meta charset="utf-8">'
            '<meta name="viewport" content="width=device-width,initial-scale=1"><title>Nova</title>'
            '<body style="margin:0;background:#05060a;color:#eef1f7;'
            'font-family:Vazirmatn,system-ui,-apple-system,Segoe UI,Roboto,sans-serif;'
            'display:grid;place-items:center;min-height:100vh">'
            '<div style="max-width:460px;padding:32px;text-align:center;border:1px solid rgba(255,255,255,.12);'
            'border-radius:16px;background:rgba(255,255,255,.04)">'
            '<div style="width:46px;height:46px;border-radius:11px;margin:0 auto 16px;'
            'background:linear-gradient(120deg,#22d3ee,#818cf8,#a855f7);display:flex;align-items:center;'
            'justify-content:center;font-weight:900;color:#05060a;font-size:22px">N</div>'
            '<h1 style="font-size:1.3rem;font-weight:800;margin:0 0 12px">Nova Wizard</h1>'
            '<p style="color:#9aa4b8;margin:0 0 6px">Open the secure link shown in the terminal window.</p>'
            '<p style="color:#9aa4b8;margin:0 0 14px" dir="rtl">لینکِ امن را که در پنجرهٔ ترمینال نشان داده شده باز کن.</p>'
            '<code style="display:block;padding:13px;border-radius:10px;background:#0b0e16;'
            'border:1px solid rgba(255,255,255,.09);color:#22d3ee;font-size:.85rem">'
            'http://127.0.0.1:8000/?token=&hellip;</code>'
            '</div></body></html>'
        )
        self.send_html(page, 401)

    def do_GET(self):
        global _oauth_error
        try:
            p = urlparse(self.path)
            if p.path == "/":
                if self.authed(p):
                    body = ui_html()
                    self.send_response(200)
                    self.send_header("Content-Type", "text/html; charset=utf-8")
                    self.send_header("Content-Length", str(len(body)))
                    self.send_header("Cache-Control", "no-store")
                    self.end_headers()
                    self.wfile.write(body)
                    return
                return self.unauth()
            if not self.authed(p): return self.send_json({"ok":False,"error":"Unauth"}, 401)
            if p.path == "/api/config":
                return self.send_json({"ok":True, "oauth_connected": bool(_oauth_token),
                    "oauth_info": {"account_id":_oauth_account_id,"account_name":_oauth_account_name} if _oauth_token else {},
                    "deployments": _deployment_history, "suggestion": suggest(),
                    "worker_exists": WORKER_FILE.exists()})
            if p.path == "/api/fetch-worker":
                try:
                    sz = fetch_worker_from_github()
                    return self.send_json({"ok":True, "size": sz, "path": str(WORKER_FILE)})
                except _CFErr as e: return self.send_json({"ok":False,"error":str(e)}, 400)
            if p.path == "/favicon.ico":
                self.send_response(204); self.end_headers(); return
            if p.path == "/api/oauth/url":
                _oauth_error = ""
                return self.send_json({"ok":True, "url": oauth_url()})
            if p.path == "/api/oauth/status":
                return self.send_json({"ok":True, "connected": bool(_oauth_token),
                    "account_id": _oauth_account_id, "account_name": _oauth_account_name,
                    "error": _oauth_error if _oauth_error else None})
            t = (STATIC_DIR / p.path.lstrip("/")).resolve()
            if STATIC_DIR.resolve() in t.parents and self.authed(p): return self.send_file(t)
            self.send_error(404)
        except Exception as e:
            traceback.print_exc(); self.send_json({"ok":False,"error":str(e)}, 500)

    def do_POST(self):
        try:
            p = urlparse(self.path)
            if not self.authed(p): return self.send_json({"ok":False,"error":"Unauth"}, 401)
            body = read_json(self)

            if p.path == "/api/accounts":
                if not _oauth_token: return self.send_json({"ok":False,"error":"Not authenticated"}, 401)
                cf = CFClient(_oauth_token)
                r = cf.req("GET", "/accounts?per_page=100")
                accts = [{"id": a.get("id"), "name": a.get("name")} for a in (r.get("result") or [])]
                return self.send_json({"ok":True, "accounts": accts})

            if p.path == "/api/deploy":
                if not _oauth_token: return self.send_json({"ok":False,"error":"Not authenticated"}, 401)
                if not WORKER_FILE.exists():
                    try: fetch_worker_from_github()
                    except _CFErr as e: return self.send_json({"ok":False,"error":f"Fetch worker.js failed: {e}"}, 400)
                cf = CFClient(_oauth_token)
                aid = (body.get("account_id") or _oauth_account_id or "").strip()
                if not aid: return self.send_json({"ok":False,"error":"Account ID required"}, 400)
                dt = (body.get("deploy_type") or "worker").strip()
                wn = safe_name(body.get("worker_name") or "", rand_name(55))
                kv = safe_name(body.get("kv_namespace") or "", f"{wn}-vault")
                d1 = safe_name(body.get("d1_name") or "", f"{wn}-db")
                extra = {}
                for k in ["PROXYIP","NAT64","HOST","PAGES_URL","DEBUG","GO2SOCKS5","BACKEND_URL"]:
                    v = (body.get(k.lower()) or "").strip()
                    if v: extra[k] = v
                result = deploy(cf, aid, wn, kv, d1, extra, dt)

                # The second door, then one claim across both addresses.
                #
                # The door used to be built only AFTER a successful claim, and the claim
                # only ever spoke to the Worker. On a brand-new Cloudflare account the
                # workers.dev subdomain does not exist yet, so the claim failed, so no
                # door was built, so the user got a single unclaimed address. Observed
                # exactly that on 2026-09-14: the hostname had still not resolved
                # twenty-five minutes later. The one address that survives a 1101 wedge,
                # and that does not depend on workers.dev at all, was gated behind
                # workers.dev resolving.
                #
                # Both addresses share the D1 store, so claiming either claims both.
                # Racing them claims through whichever is ready first, which SHORTENS
                # the unclaimed window rather than lengthening it. The invariant that
                # matters is unchanged: neither address is shown to the user until a
                # password exists on it.
                #
                # The second door.
                #
                # Measured 2026-09-14 across the fleet: of 230 wedged panels that had a
                # pages.dev door, 229 Workers were returning 1101 and 227 of the doors
                # were still serving. A Worker slot can wedge for reasons that have
                # nothing to do with the code on it, and when that happens the Pages
                # address is what is left. Iran also filters workers.dev and pages.dev
                # separately, so two addresses survive one filtering decision.
                #
                # Same database, same secret paths, same UUID, so it is one panel on two
                # addresses rather than two panels. Built AFTER the claim: a door raised
                # before a password exists is a panel anyone can take.
                #
                # Best effort. A panel with one working address is a successful install,
                # so nothing here may fail the deploy.
                door_url = ""
                if dt != "pages":
                    try:
                        door = deploy(cf, aid, f"{wn}-door", kv, d1, extra, "pages",
                                      paths={**result.get("paths", {}), "skip_claim": True})
                        door_url = door.get("worker_url") or ""
                    except Exception as e:
                        result["door_error"] = str(e)[:200]

                # One claim, both addresses, first one to answer wins.
                password = rand_password()
                claimed_on = claim_panel([u for u in (result.get("worker_url"), door_url) if u],
                                         password)
                result["claimed"] = bool(claimed_on)
                result["admin_pass"] = password if claimed_on else ""
                result["set_password"] = not claimed_on
                result["claimed_on"] = claimed_on

                # Only advertise the door once the panel has a password on it.
                if door_url and claimed_on:
                    login = (result.get("paths") or {}).get("login") or ""
                    result["door_url"] = door_url
                    result["door_panel_url"] = f"{door_url}/{login}" if login else door_url

                report_install(result.get("worker_url"))
                result["id"] = secrets.token_hex(8)
                result["account_id"] = aid
                result["status"] = "active"
                _deployment_history.insert(0, result)
                if len(_deployment_history) > 50: _deployment_history[:] = _deployment_history[:50]
                return self.send_json({"ok":True, "result": result, "suggestion": suggest()})

            if p.path == "/api/delete_deploy":
                if not _oauth_token: return self.send_json({"ok":False,"error":"Not authenticated"}, 401)
                cf = CFClient(_oauth_token)
                aid = (body.get("account_id") or _oauth_account_id or "").strip()
                wn = safe_name(body.get("worker_name") or "")
                kv_id = (body.get("kv_id") or "").strip()
                kv_t = safe_name(body.get("kv_namespace") or "", "") if body.get("kv_namespace") else ""
                d1_id = (body.get("d1_id") or "").strip()
                dt = (body.get("deploy_type") or "worker").strip()
                if not aid: return self.send_json({"ok":False,"error":"Account ID required"}, 400)
                res = cleanup(cf, aid, wn, kv_id, kv_t, d1_id, dt)
                did = (body.get("deployment_id") or "").strip()
                if did:
                    _deployment_history[:] = [d for d in _deployment_history if d.get("id") != did]
                res["message"] = "Cleanup done"
                return self.send_json({"ok":True, "result": res})

            self.send_json({"ok":False,"error":"Not found"}, 404)
        except Exception as e:
            traceback.print_exc()
            st = 500
            if isinstance(e, _CFErr):
                st = e.status if (e.status and 400 <= e.status < 600) else 400
            self.send_json({"ok":False,"error":str(e)}, st)

    def log_message(self, fmt, *a):
        print(f"  [{self.log_date_time_string()}] {fmt % a}")

# ─── main ──────────────────────────────────────────────────

def main():
    start_oauth_server()
    host = os.environ.get("NOVA_HOST", "127.0.0.1")
    port = int(os.environ.get("NOVA_PORT", "8000"))
    httpd = ThreadingHTTPServer((host, port), Handler)
    url = f"http://{host}:{port}/?token={LOCAL_TOKEN}"
    print()
    print("=" * 54)
    print("  Nova OAuth Wizard")
    print("  Cloudflare Worker + KV + D1 Deployer")
    print("=" * 54)
    print(f"  URL:  {url}")
    print(f"  JS:   {WORKER_FILE}")
    if not WORKER_FILE.exists(): print("  [!] worker.js not found!")
    print()
    print("  1. Open browser")
    print("  2. Click 'Login with Cloudflare'")
    print("  3. Authorize on Cloudflare")
    print("  4. Enter names + Deploy")
    print()
    print("  Ctrl+C to stop.")
    print("=" * 54)
    print()
    import webbrowser as _wb
    threading.Timer(1.5, lambda: _wb.open(url)).start()
    try: httpd.serve_forever()
    except KeyboardInterrupt: print("\n  Stopped.")
    finally: revoke_oauth_token()

if __name__ == "__main__": main()
