#!/usr/bin/env python3
"""Fold static/index.html into nova_wizard.py so the tool is one file.

The wizard used to need `git clone`, purely because its UI lived in a second
file. That cost every user a git install and three commands instead of one.
The UI is now carried inside the script, gzipped and base64'd, and
static/index.html stays the source you edit.

Run this after changing static/index.html, then commit both. `--check` verifies
the two are in sync and exits non-zero if they are not, so a forgotten
regenerate is caught rather than shipped.
"""
import base64, gzip, io, re, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "static" / "index.html"
DST = ROOT / "nova_wizard.py"
BEGIN = "# --- BEGIN EMBEDDED UI (generated by scripts/embed_ui.py, do not edit) ---"
END = "# --- END EMBEDDED UI ---"


def payload() -> str:
    return base64.b64encode(gzip.compress(SRC.read_bytes(), 9)).decode("ascii")


def block(data: str) -> str:
    lines = [data[i:i + 96] for i in range(0, len(data), 96)]
    body = "\n".join(f'    "{ln}"' for ln in lines)
    return f'{BEGIN}\n_EMBEDDED_UI_B64 = (\n{body}\n)\n{END}'


def current(text: str) -> str | None:
    m = re.search(re.escape(BEGIN) + r"\n(.*?)\n" + re.escape(END), text, re.S)
    if not m:
        return None
    return "".join(re.findall(r'"([A-Za-z0-9+/=]*)"', m.group(1)))


def main() -> int:
    text = DST.read_text(encoding="utf8")
    want = payload()
    if "--check" in sys.argv:
        have = current(text)
        if have is None:
            print("embed_ui: no embedded block in nova_wizard.py"); return 1
        if have != want:
            print("embed_ui: embedded UI is STALE, run scripts/embed_ui.py"); return 1
        print("embed_ui: embedded UI matches static/index.html"); return 0
    new = block(want)
    if current(text) is None:
        print("embed_ui: no marker block found to replace"); return 1
    text = re.sub(re.escape(BEGIN) + r"\n.*?\n" + re.escape(END), lambda _: new, text, flags=re.S)
    DST.write_text(text, encoding="utf8")
    print(f"embed_ui: embedded {SRC.stat().st_size:,} bytes of UI")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
